---
- name: "Server configuration"
  hosts: "all"
  become: true
  tasks:
    - name: "Join worker to k8s master"
      register: command_output
      ansible.builtin.shell: |
        token=$(cat /vagrant/.kube/k8s-token.txt)
        echo "Worker is joining to -> master"
        echo "$token"
        microk8s join master:25000/$token --worker
        exit 0 
    - debug:
        var: command_output.stdout_lines