---
- name: "Server configuration"
  hosts: "all"
  become: true
  tasks:
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
    - name: Install microk8s
      snap:
        name: microk8s
        classic: true
    - name: Add user to group microk8s
      ansible.builtin.shell: |
        usermod -a -G microk8s vagrant
        echo "alias kubectl='microk8s.kubectl'" > /home/vagrant/.bash_aliases
        chown vagrant:vagrant /home/vagrant/.bash_aliases
        echo "alias kubectl='microk8s.kubectl'" > /root/.bash_aliases
        chown root:root /root/.bash_aliases
    - name: Enable microk8s addons
      ansible.builtin.shell:
        cmd: "microk8s enable {{item}}"
      with_items:
        - "{{addons}}"
    - name: Wait status
      ansible.builtin.shell: |
        microk8s status --wait-ready
    - debug:
        var: command_output.stdout_lines